### ISSUE TITLE
Create mode switch component for toolbar configurator

### ISSUE THREAD

**Issue by oleq** [cksource/samples-framework#13]
It can be either a samples-framework- or toolbar configurator-specific component. I'd rather see it a generic one, to be honest.

![toolbarconfigurator-002](https://cloud.githubusercontent.com/assets/1099479/6559329/7372c142-c682-11e4-8703-2d416bc73b93.png)

**Comment by norin89** [comment]
I put simple code snipped on [JSFiddle](http://jsfiddle.net/norin89/hd9x7ent/3/) to show you how to achieve it with pure CSS.

**Comment by adelura** [comment]
Fixed with https://github.com/cksource/samples-framework/commit/0cdab35f34ed6cf4a216ec7fcddcddac44330145.
