### ISSUE TITLE
Result CSS should be included?

### ISSUE THREAD

**Issue by adelura** [cksource/samples-framework#33]
Or at least result for `docs` and `samples`.

**Comment by Reinmar** [comment]
No - we decided to not include result CSS.

**Comment by Reinmar** [comment]
> No - we decided to not include result CSS.

Reasoning - it makes commits messier.

**Comment by adelura** [comment]
I asked because github pages doesn't work, because there are no CSS`es.

**Comment by Reinmar** [comment]
So fix the `gh-pages` branch by pushing there contents with CSS. Also, in the index of the repository there should be `index.html`. In other words - contents of `gh-pages` will not equal contents of `master`.

**Comment by adelura** [comment]
Yep, and we decided not to use github pages for this project.
