### ISSUE TITLE
Add expand/collapse switcher

### ISSUE THREAD

**Issue by adelura** [cksource/samples-framework#34]
Functionality with clickable button which will expand/collapse related box.
![img](https://cloud.githubusercontent.com/assets/37869/6731939/e2b53350-ce48-11e4-9bc9-4121e65e4136.png)

**Comment by oleq** [comment]
I'm OK with it as long as it remains a very simple JS component.

**Comment by adelura** [comment]
We can do it with CSS only but it won't work in IE8.

**Comment by adelura** [comment]
I created `toggler` in https://github.com/cksource/samples-framework/commit/7252a2aaa8f4926db57a98a944bc947f40179c594. This won't work in IE<10 because of `classList`. Please let me know what is not okay if any.

**Comment by oleq** [comment]
> This won't work in IE<10 because of `classList`.

It got to be IE8+. Sorry. Also the hash does not work (rebased?).

**Comment by oleq** [comment]
Also:
* `@import url('../icon/icon');` is rather obsolete. Each derivative project includes it anyway.
* No license banner in `toggler.less`.
* Make 

 > Please note: You should include javascript file: /components/toggler/js/toggler.js

 a highlighted HTML snippet (`<script ...>`). Also mention to put it at the bottom of the document since we don't wait for `DOMContentLoaded`.
