### ISSUE TITLE
Fix all spaces in code snippets

### ISSUE THREAD

**Issue by adelura** [cksource/samples-framework#38]
Should be tabs instead of spaces.

**Comment by Reinmar** [comment]
https://github.com/cksource/samples-framework/commit/5697a05ddc8f647c54d45b2efe69b3e964880704#diff-634f98626494af09e9783e1f5e0c045dR155

2? We do use 4.

**Comment by Reinmar** [comment]
Besides that there's no point in defining `-o-tab-spaces`.

**Comment by adelura** [comment]
Opera mini and opera mobile requires `-o` frefix.

**Comment by Reinmar** [comment]
I don't think that Blink based Operas require now the `-o` prefix.

**Comment by adelura** [comment]
http://caniuse.com/#search=tab-size click "Show all" button.

**Comment by Reinmar** [comment]
Uh, that's sad. Ok, you're right then.

**Comment by Reinmar** [comment]
I mean - it's only because of Opera Mini, but it doesn't really mean anything for us, since it's not supported by us.
